# Generated by Django 3.0.8 on 2020-08-01 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('studio', models.CharField(max_length=50)),
                ('cover', models.CharField(max_length=500)),
                ('resume', models.TextField()),
                ('note', models.IntegerField()),
                ('available', models.BooleanField(default=True)),
                ('trailer', models.CharField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_api.Genre')),
            ],
        ),
    ]
