# Generated by Django 3.0.8 on 2020-08-01 08:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_api', '0002_auto_20200801_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='note',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
