# Generated by Django 3.0.8 on 2020-08-01 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_api', '0003_auto_20200801_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editor',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='game',
            name='editor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='game_api.Editor'),
        ),
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='game_api.Genre'),
        ),
    ]
