# Generated by Django 3.0.8 on 2020-08-01 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_api', '0004_auto_20200801_1200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='note',
            new_name='average',
        ),
        migrations.AlterField(
            model_name='game',
            name='editor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_api.Editor'),
        ),
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_api.Genre'),
        ),
    ]
