# Generated by Django 3.0.8 on 2020-08-01 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_api', '0005_auto_20200801_1323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='genre',
            new_name='name',
        ),
    ]
