# Generated by Django 3.0.8 on 2020-08-02 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_api', '0007_news'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='New',
        ),
    ]
