# Generated by Django 3.0.8 on 2020-08-02 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_api', '0008_auto_20200802_0958'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='New',
            new_name='News',
        ),
    ]
