# Generated by Django 3.0.8 on 2020-08-03 20:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_api', '0011_auto_20200803_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='average',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
