# Generated by Django 3.0.8 on 2020-08-06 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_api', '0013_auto_20200805_2109'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='game',
            name='test_img1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='test_img2',
        ),
        migrations.RemoveField(
            model_name='game',
            name='test_img3',
        ),
        migrations.RemoveField(
            model_name='game',
            name='test_img4',
        ),
        migrations.RemoveField(
            model_name='game',
            name='test_img',
        ),
        migrations.AddField(
            model_name='game',
            name='test_img',
            field=models.ManyToManyField(to='game_api.TestImg'),
        ),
    ]
