# Generated by Django 3.0.8 on 2020-08-06 12:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game_api', '0016_auto_20200806_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='trailer',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
