# Generated by Django 3.0.8 on 2020-08-06 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_api', '0017_auto_20200806_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='trailer',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
