# Generated by Django 3.0.8 on 2020-08-06 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_api', '0018_auto_20200806_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='plateform',
            field=models.ManyToManyField(blank=True, to='game_api.Plateform'),
        ),
    ]
