# Generated by Django 3.0.8 on 2020-08-06 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_api', '0020_auto_20200806_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editor',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
