# Generated by Django 3.0.8 on 2020-08-06 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_api', '0021_auto_20200806_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editor',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='game',
            name='editor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='game_api.Editor'),
        ),
    ]
