# Generated by Django 3.0.8 on 2020-08-06 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_api', '0022_auto_20200806_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editor',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game_api.Editor'),
        ),
        migrations.AlterField(
            model_name='game',
            name='resume',
            field=models.TextField(blank=True),
        ),
    ]
